spring.application.name=portfolio

server.port=${PORT:8080}

# SMTP Mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.debug=false

# logging levels
logging.level.org.springframework.mail=INFO
logging.level.com.suprun=INFO