name: Keeps server alive because the Render free tier stops the instance after 15 minutes of inactivity

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping API
        run: curl https://yuriisuprun.onrender.com/internal/ping